### ISSUE TITLE
Используется некорректный протокол безопасности

### ISSUE THREAD

**Issue by Dia6lo** [hflabs/suggestions-csharp#1]
При любом запросе вылетает
```csharp
System.Security.Authentication.AuthenticationException : Удаленный сертификат недействителен согласно результатам проверки подлинности.
```

При смене `SecurityProtocolType.Ssl3` на `SecurityProtocolType.Tls` всё приходит в норму.

**Comment by algenon** [comment]
Спасибо, что заметили! Сейчас SSL3 работает, но вообще лучше использовать TLS. Обновляйтесь на релиз [16.10.1](https://github.com/hflabs/suggestions-csharp/releases/tag/16.10.1).
