### ISSUE TITLE
Отсутствует адрес банка в классе BankData

### ISSUE THREAD

**Issue by S-le** [hflabs/suggestions-csharp#6]
При обращении к методу QueryBank() класса SuggestClient возвращается коллекция данных о банках. Свойство BankData.address содержит экземпляр класса AddressData. Но дело в том, что все свойства этого класса равны null. 
Например, по запросу "сбербанк" (значений возвращается больше, оставил только "ДАЛЬНЕВОСТОЧНЫЙ БАНК ПАО СБЕРБАНК", в других банках, тоже нет значений адреса):
`[
  {
      "data": {
      "address": {
        "source": null,
        "postal_code": null,
        "country": null,
        "region_fias_id": null,
        "region_kladr_id": null,
        "region_with_type": null,
        "region_type": null,
        "region_type_full": null,
        "region": null,
        "area_fias_id": null,
        "area_kladr_id": null,
        "area_with_type": null,
        "area_type": null,
        "area_type_full": null,
        "area": null,
        "city_fias_id": null,
        "city_kladr_id": null,
        "city_with_type": null,
        "city_type": null,
        "city_type_full": null,
        "city": null,
        "city_area": null,
        "city_district_fias_id": null,
        "city_district_kladr_id": null,
        "city_district_with_type": null,
        "city_district_type": null,
        "city_district_type_full": null,
        "city_district": null,
        "settlement_fias_id": null,
        "settlement_kladr_id": null,
        "settlement_with_type": null,
        "settlement_type": null,
        "settlement_type_full": null,
        "settlement": null,
        "street_fias_id": null,
        "street_kladr_id": null,
        "street_with_type": null,
        "street_type": null,
        "street_type_full": null,
        "street": null,
        "house_fias_id": null,
        "house_kladr_id": null,
        "house_type": null,
        "house_type_full": null,
        "house": null,
        "block_type": null,
        "block_type_full": null,
        "block": null,
        "flat_type": null,
        "flat_type_full": null,
        "flat": null,
        "flat_area": null,
        "square_meter_price": null,
        "flat_price": null,
        "postal_box": null,
        "fias_id": null,
        "fias_level": null,
        "kladr_id": null,
        "capital_marker": null,
        "okato": null,
        "oktmo": null,
        "tax_office": null,
        "tax_office_legal": null,
        "timezone": null,
        "geo_lat": null,
        "geo_lon": null,
        "qc_geo": null,
        "beltway_hit": null,
        "beltway_distance": null,
        "history_values": null,
        "metro": null
      },
      "bic": "040813608",
      "swift": "SABRRU8KVLD",
      "registration_number": "1481/1654",
      "correspondent_account": "30101810600000000608",
      "name": {
        "payment": "ДАЛЬНЕВОСТОЧНЫЙ БАНК ПАО СБЕРБАНК",
        "full": "СБЕРБАНК РОССИИ ДАЛЬНЕВОСТОЧНЫЙ БАНК",
        "short": "null…"
      },
      "okpo": "02785100",
      "opf": {
        "type": 2,
        "full": "Территориальные управления Сбербанка",
        "short": "ТУСБ"
      },
      "phone": null,
      "rkc":
        "{\"opf\":{\"type\":\"OTHER\",\"full\":\"Отделение (НБ), не ведущее баланс\",\"short\":\"ОНБ\"},\"name\":{\"payment\":\"ОТДЕЛЕНИЕ ХАБАРОВСК\",\"full\":null,\"short\":null},\"bic\":\"040813001\",\"swift\":null,\"okpo\":\"58923241\",\"correspondent_account\":null,\"registration_number\":null,\"rkc\":null,\"address\":{\"value\":\"680042, ХАБАРОВСК, УЛ.ВОРОНЕЖСКАЯ,154\",\"unrestricted_value\":\"680042, ХАБАРОВСК, УЛ.ВОРОНЕЖСКАЯ,154\",\"data\":null},\"phones\":null,\"state\":{\"status\":\"ACTIVE\",\"actuality_date\":1522800000000,\"registration_date\":759024000000,\"liquidation_date\":null}}",
      "state": {
        "actuality_date": "1522800000000",
        "registration_date": "759024000000",
        "liquidation_date": null,
        "status": "0…"
      }
    },
    "value": "ДАЛЬНЕВОСТОЧНЫЙ БАНК ПАО СБЕРБАНК",
    "unrestricted_value": "ДАЛЬНЕВОСТОЧНЫЙ БАНК ПАО СБЕРБАНК"
  }
]`

**Comment by nalgeon** [comment]
Спасибо! Исправлено в релизе [17.10.2](https://github.com/hflabs/suggestions-csharp/releases/tag/17.10.2)
